site_name: Apache Kafka Streams Studies
repo_url: https://github.com/jbcodeforce/kafka-streams-samples.git
docs_dir: docs
site_dir: public
edit_uri: edit/master/docs
nav:
  - Introduction: index.md
  - Kafka streaming:
    - EDA kstreams note: https://ibm-cloud-architecture.github.io/refarch-eda/technology/kafka-streams/
    - Item aggregator: https://github.com/ibm-cloud-architecture/refarch-eda-item-inventory
    - Store aggregator: https://github.com/ibm-cloud-architecture/refarch-eda-store-inventory
  - Go Back Home: https://jbcodeforce.github.io/
theme: 
  name: material
  feature:
    tabs: true
  palette:
    scheme: default
    primary: 'magenta dark'
  language: en
  features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs.sticky
      - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'twitter'
      link: 'https://twitter.com/agileitarch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details